# Generated by Django 4.0.5 on 2022-06-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['number'], 'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
        migrations.AddField(
            model_name='season',
            name='status',
            field=models.CharField(choices=[('END', 'Ended'), ('ACT', 'Active'), ('FUT', 'Future')], default='FUT', max_length=3),
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='numeral',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
