# Generated by Django 4.0.5 on 2022-06-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_alter_season_options_season_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='numeral',
        ),
        migrations.AddField(
            model_name='nft',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seasons.season'),
            preserve_default=False,
        ),
    ]
